### ISSUE TITLE
Add Token to Wallet "can't find backend for script_hash H256

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/godwoken-web3#248]
`env: commit bbf09f464f4e07bfefd24fe0f54c5cf1c2d6eeb0 
compatibility-changes`

```
15:24:15 0|gw-web3  | rawL2Transaction: {
15:24:15 0|gw-web3  |   "from_id": "0x5",
15:24:15 0|gw-web3  |   "to_id": "0x151",
15:24:15 0|gw-web3  |   "nonce": "0x0",
15:24:15 0|gw-web3  |   "args": "0xffffff504f4c5900000000010000000001000000000000000000000000000000000000000000000000000000000000002400000070a082310000000000000000000000000c1efcca2bcb65a532274f3ef24c044ef4ab6d73"
15:24:15 0|gw-web3  | }
15:24:15 0|gw-web3  | Call gw rpc "gw_execute_raw_l2transaction" error: JSONRPCError: server error {"code":0,"message":"can't find backend for script_hash H256([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])"}
15:24:15 0|gw-web3  | [error]  JSONRPC Server Error: [bound call] RpcError: Cannot read property 'last_log' of undefined RpcError: Cannot read property 'last_log' of undefined
15:24:15 0|gw-web3  |     at Eth.call (/godwoken-web3/packages/api-server/lib/methods/modules/eth.js:331:19)
15:24:15 0|gw-web3  |     at runMicrotasks (<anonymous>)
15:24:15 0|gw-web3  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
15:24:15 0|gw-web3  |     at async Eth.call (/godwoken-web3/packages/api-server/lib/methods/validator.js:28:20)
15:24:15 0|gw-web3  |     at async Server.methods.<computed> (/godwoken-web3/packages/api-server/lib/methods/index.js:49:36)
```

`Steps to reproduce
Using E2E`—— `Add Token to Wallet`

**Comment by Dawn-githup** [comment]
Fixed
