### ISSUE TITLE
[BUG] eth_ Call query prompts' check balance err: ScriptHashNotFound 'error

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/godwoken-web3#574]
## **Version**
- Godwoken v1
- https://godwoken-alphanet-v1.ckbapp.dev

## **Describe the bug**
eth_ Call query prompts' check balance err: ScriptHashNotFound 'error 

**To Reproduce**

Specific operation reference code 
[https://github.com/cryptape/evm-testing/pull/30/files#diff-8fa6f6c2d0e437b3ec016089eab07b8187db5c91bf9a75ee32227bd8da257057](https://github.com/cryptape/evm-testing/pull/30/files#diff-8fa6f6c2d0e437b3ec016089eab07b8187db5c91bf9a75ee32227bd8da257057)

**Screenshots or Logs**

```log
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 19 }
jsonRpcResponse: { jsonrpc: '2.0', id: 19, result: '0x315de' }
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 20 }
jsonRpcResponse: { jsonrpc: '2.0', id: 20, result: '0x315de' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionCount',
  params: [ '0x4866f8c3d21cdb7cff6689576caea91a475ea98a', 'latest' ],
  id: 22
}
jsonRpcResponse: { jsonrpc: '2.0', id: 22, result: '0xa919' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x4866f8c3d21cdb7cff6689576caea91a475ea98a',
      to: '0x6f0073566c5dcd9d9ce36bbb90355f7118e5c7ba',
      data: '0xf8b2cb4f0000000000000000000000004866f8c3d21cdb7cff6689576caea91a475ea98a'
    },
    'latest'
  ],
  id: 21
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 21,
  error: { code: -32600, message: 'check balance err: ScriptHashNotFound' }
}

Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x4866f8c3d21CDb7CFf6689576cAeA91A475EA98a","to":"0x6F0073566c5Dcd9d9CE36Bbb90355f7118E5c7bA","data":"0xf8b2cb4f0000000000000000000000004866f8c3d21cdb7cff6689576caea91a475ea98a","accessList":null}, error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (D:\\CryptCode\\js-Test\\evm-test\\evm-testing\\node_modules\\hardhat\\internal\\core\\providers\\http.js:50:23)\n    at LocalAccountsProvider.request (D:\\CryptCode\\js-Test\\evm-test\\evm-testing\\node_modules\\hardhat\\internal\\core\\providers\\accounts.js:143:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async EthersProviderWrapper.send (D:\\CryptCode\\js-Test\\evm-test\\evm-testing\\node_modules\\@nomiclabs\\hardhat-ethers\\internal\\ethers-provider-wrapper.js:11:24)","code":-32600,"_isProviderError":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (node_modules\@ethersproject\logger\lib\index.js:238:21)
    at Logger.throwError (node_modules\@ethersproject\logger\lib\index.js:247:20)
    at checkError (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:108:16)
    at EthersProviderWrapper.<anonymous> (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:751:47)
    at step (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by RetricSu** [comment]
unable to reproduce it now. Consider the issue where Godwoken read-only node is not synced to the latest with full node.

**Comment by Dawn-githup** [comment]
> 现在无法重现。考虑 Godwoken 只读节点未同步到最新全节点的问题。

**Comment by Dawn-githup** [comment]
> unable to reproduce it now. Consider the issue where Godwoken read-only node is not synced to the latest with full node.

Later, I'll try to see if it can reappear
